/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.panelController.RoomMapController;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import javax.swing.*;

/**
 *
 * @author lminh
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardView() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/hotel.png"));
        setIconImage(icon.getImage());
        btnRoomMap.setBackground(new Color(140,23,17));
        panelBoderRoomMap.setVisible(true);
        panelBoderRoomManage.setVisible(false);
        panelBorderPayment.setVisible(false);
        panelBorderStatis.setVisible(false);
        panelBorderInforPerson.setVisible(false);
        panelBorderUserMgt.setVisible(false);
        panelBorderCusMgt.setVisible(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDashboard = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelRoomMap = new javax.swing.JPanel();
        panelBoderRoomMap = new javax.swing.JPanel();
        btnRoomMap = new javax.swing.JButton();
        panelRoomManage = new javax.swing.JPanel();
        panelBoderRoomManage = new javax.swing.JPanel();
        btnRoomManage = new javax.swing.JButton();
        panelPayment = new javax.swing.JPanel();
        panelBorderPayment = new javax.swing.JPanel();
        btnPayment = new javax.swing.JButton();
        panelStatistical = new javax.swing.JPanel();
        panelBorderStatis = new javax.swing.JPanel();
        btnStatistical = new javax.swing.JButton();
        panelCustomerManage = new javax.swing.JPanel();
        panelBorderCusMgt = new javax.swing.JPanel();
        btnCustomerManagement = new javax.swing.JButton();
        panelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelnforPerson = new javax.swing.JPanel();
        panelBorderInforPerson = new javax.swing.JPanel();
        btnPersonInfor = new javax.swing.JButton();
        panelUserManage = new javax.swing.JPanel();
        panelBorderUserMgt = new javax.swing.JPanel();
        btnUserManagement = new javax.swing.JButton();
        panelScreen = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(175, 17, 23));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 440));

        panelRoomMap.setBackground(new java.awt.Color(175, 17, 23));
        panelRoomMap.setLayout(new java.awt.BorderLayout());

        panelBoderRoomMap.setBackground(new java.awt.Color(248, 138, 7));
        panelBoderRoomMap.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout panelBoderRoomMapLayout = new javax.swing.GroupLayout(panelBoderRoomMap);
        panelBoderRoomMap.setLayout(panelBoderRoomMapLayout);
        panelBoderRoomMapLayout.setHorizontalGroup(
            panelBoderRoomMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBoderRoomMapLayout.setVerticalGroup(
            panelBoderRoomMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelRoomMap.add(panelBoderRoomMap, java.awt.BorderLayout.LINE_START);

        btnRoomMap.setBackground(new java.awt.Color(175, 17, 23));
        btnRoomMap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRoomMap.setForeground(new java.awt.Color(255, 255, 255));
        btnRoomMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home_3.png"))); // NOI18N
        btnRoomMap.setText("Sơ đồ phòng");
        btnRoomMap.setBorder(null);
        btnRoomMap.setBorderPainted(false);
        buttonGroupDashboard.add(btnRoomMap);
        btnRoomMap.setFocusPainted(false);
        btnRoomMap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelRoomMap.add(btnRoomMap, java.awt.BorderLayout.CENTER);

        panelRoomManage.setBackground(new java.awt.Color(175, 17, 23));
        panelRoomManage.setLayout(new java.awt.BorderLayout());

        panelBoderRoomManage.setBackground(new java.awt.Color(248, 148, 7));
        panelBoderRoomManage.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout panelBoderRoomManageLayout = new javax.swing.GroupLayout(panelBoderRoomManage);
        panelBoderRoomManage.setLayout(panelBoderRoomManageLayout);
        panelBoderRoomManageLayout.setHorizontalGroup(
            panelBoderRoomManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBoderRoomManageLayout.setVerticalGroup(
            panelBoderRoomManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelRoomManage.add(panelBoderRoomManage, java.awt.BorderLayout.LINE_START);

        btnRoomManage.setBackground(new java.awt.Color(175, 17, 23));
        btnRoomManage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRoomManage.setForeground(new java.awt.Color(255, 255, 255));
        btnRoomManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Request Service_2.png"))); // NOI18N
        btnRoomManage.setText("Quản lý phòng");
        btnRoomManage.setBorder(null);
        buttonGroupDashboard.add(btnRoomManage);
        btnRoomManage.setFocusPainted(false);
        btnRoomManage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelRoomManage.add(btnRoomManage, java.awt.BorderLayout.CENTER);

        panelPayment.setBackground(new java.awt.Color(175, 17, 23));
        panelPayment.setLayout(new java.awt.BorderLayout());

        panelBorderPayment.setBackground(new java.awt.Color(248, 148, 7));
        panelBorderPayment.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout panelBorderPaymentLayout = new javax.swing.GroupLayout(panelBorderPayment);
        panelBorderPayment.setLayout(panelBorderPaymentLayout);
        panelBorderPaymentLayout.setHorizontalGroup(
            panelBorderPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBorderPaymentLayout.setVerticalGroup(
            panelBorderPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelPayment.add(panelBorderPayment, java.awt.BorderLayout.LINE_START);

        btnPayment.setBackground(new java.awt.Color(175, 17, 23));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Card_Payment.png"))); // NOI18N
        btnPayment.setText("Thanh toán");
        btnPayment.setBorder(null);
        buttonGroupDashboard.add(btnPayment);
        btnPayment.setFocusPainted(false);
        btnPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelPayment.add(btnPayment, java.awt.BorderLayout.CENTER);

        panelStatistical.setBackground(new java.awt.Color(175, 17, 23));
        panelStatistical.setLayout(new java.awt.BorderLayout());

        panelBorderStatis.setBackground(new java.awt.Color(248, 148, 7));
        panelBorderStatis.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout panelBorderStatisLayout = new javax.swing.GroupLayout(panelBorderStatis);
        panelBorderStatis.setLayout(panelBorderStatisLayout);
        panelBorderStatisLayout.setHorizontalGroup(
            panelBorderStatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBorderStatisLayout.setVerticalGroup(
            panelBorderStatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelStatistical.add(panelBorderStatis, java.awt.BorderLayout.LINE_START);

        btnStatistical.setBackground(new java.awt.Color(175, 17, 23));
        btnStatistical.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStatistical.setForeground(new java.awt.Color(255, 255, 255));
        btnStatistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Graph Report Script.png"))); // NOI18N
        btnStatistical.setText("Thống kê");
        btnStatistical.setBorder(null);
        buttonGroupDashboard.add(btnStatistical);
        btnStatistical.setFocusPainted(false);
        btnStatistical.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelStatistical.add(btnStatistical, java.awt.BorderLayout.CENTER);

        panelCustomerManage.setBackground(new java.awt.Color(175, 17, 23));
        panelCustomerManage.setLayout(new java.awt.BorderLayout());

        panelBorderCusMgt.setBackground(new java.awt.Color(248, 148, 7));
        panelBorderCusMgt.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout panelBorderCusMgtLayout = new javax.swing.GroupLayout(panelBorderCusMgt);
        panelBorderCusMgt.setLayout(panelBorderCusMgtLayout);
        panelBorderCusMgtLayout.setHorizontalGroup(
            panelBorderCusMgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBorderCusMgtLayout.setVerticalGroup(
            panelBorderCusMgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelCustomerManage.add(panelBorderCusMgt, java.awt.BorderLayout.LINE_START);

        btnCustomerManagement.setBackground(new java.awt.Color(175, 17, 23));
        btnCustomerManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCustomerManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Graph Report Script.png"))); // NOI18N
        btnCustomerManagement.setText("Quản lí khách hàng");
        btnCustomerManagement.setBorder(null);
        buttonGroupDashboard.add(btnCustomerManagement);
        btnCustomerManagement.setFocusPainted(false);
        btnCustomerManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelCustomerManage.add(btnCustomerManagement, java.awt.BorderLayout.CENTER);

        panelLogo.setBackground(new java.awt.Color(175, 17, 23));
        panelLogo.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Firebase.png"))); // NOI18N
        panelLogo.add(jLabel1, java.awt.BorderLayout.CENTER);

        panelnforPerson.setBackground(new java.awt.Color(175, 17, 23));
        panelnforPerson.setLayout(new java.awt.BorderLayout());

        panelBorderInforPerson.setBackground(new java.awt.Color(248, 148, 7));
        panelBorderInforPerson.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout panelBorderInforPersonLayout = new javax.swing.GroupLayout(panelBorderInforPerson);
        panelBorderInforPerson.setLayout(panelBorderInforPersonLayout);
        panelBorderInforPersonLayout.setHorizontalGroup(
            panelBorderInforPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBorderInforPersonLayout.setVerticalGroup(
            panelBorderInforPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelnforPerson.add(panelBorderInforPerson, java.awt.BorderLayout.LINE_START);

        btnPersonInfor.setBackground(new java.awt.Color(175, 17, 23));
        btnPersonInfor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPersonInfor.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Customer.png"))); // NOI18N
        btnPersonInfor.setText("Thông tin cá nhân");
        btnPersonInfor.setBorder(null);
        buttonGroupDashboard.add(btnPersonInfor);
        btnPersonInfor.setFocusPainted(false);
        btnPersonInfor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelnforPerson.add(btnPersonInfor, java.awt.BorderLayout.CENTER);

        panelUserManage.setBackground(new java.awt.Color(175, 17, 23));
        panelUserManage.setLayout(new java.awt.BorderLayout());

        panelBorderUserMgt.setBackground(new java.awt.Color(248, 148, 7));
        panelBorderUserMgt.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout panelBorderUserMgtLayout = new javax.swing.GroupLayout(panelBorderUserMgt);
        panelBorderUserMgt.setLayout(panelBorderUserMgtLayout);
        panelBorderUserMgtLayout.setHorizontalGroup(
            panelBorderUserMgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBorderUserMgtLayout.setVerticalGroup(
            panelBorderUserMgtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelUserManage.add(panelBorderUserMgt, java.awt.BorderLayout.LINE_START);

        btnUserManagement.setBackground(new java.awt.Color(175, 17, 23));
        btnUserManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnUserManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Graph Report Script.png"))); // NOI18N
        btnUserManagement.setText("Quản lí nhân viên");
        btnUserManagement.setBorder(null);
        buttonGroupDashboard.add(btnUserManagement);
        btnUserManagement.setFocusPainted(false);
        btnUserManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelUserManage.add(btnUserManagement, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRoomMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRoomManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelStatistical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelnforPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(panelCustomerManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUserManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRoomMap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRoomManage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCustomerManage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelUserManage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelnforPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelScreen.setMaximumSize(new java.awt.Dimension(800, 600));
        panelScreen.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(248, 138, 7));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnClose.setBackground(new java.awt.Color(248, 138, 7));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Multiply_3.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setFocusPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 760, Short.MAX_VALUE)
                .addComponent(btnClose))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param listener
     * @param args the command line arguments
     */
    
    public void setBtnRoomMapAct(ActionListener listener) {
        btnRoomMap.addActionListener(listener);
    }
    
    public void setBtnRoomManage(ActionListener listener) {
        btnRoomManage.addActionListener(listener);
    }
    
    public void setBtnPayment(ActionListener listener) {
        btnPayment.addActionListener(listener);
    }
    
    public void setBtnStatistical(ActionListener listener) {
        btnStatistical.addActionListener(listener);
    }
    
    public void setBtnPersonInfor(ActionListener listener) {
        btnPersonInfor.addActionListener(listener);
    }
    public void setBtnCloseAct(ActionListener listener) {
        btnClose.addActionListener(listener);
    }
    public void setBtnUserManagement(ActionListener listener) {btnUserManagement.addActionListener(listener);}
    public void setBtnCustomerManagement(ActionListener listener) {btnCustomerManagement.addActionListener(listener);}

    public void setEnableBtnUserMgt(boolean enable) {
        btnUserManagement.setEnabled(enable);
    }

    public void addPanelToPanelScreen(JPanel jPanel, String namePanel) {
        panelScreen.add(jPanel,namePanel);
    }
    
    public JPanel getPanelScreen() {
        return panelScreen;
    }
    
//    public String getNamePanelRoomMap() {
//        return ""
//    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    public javax.swing.JButton btnCustomerManagement;
    public javax.swing.JButton btnPayment;
    public javax.swing.JButton btnPersonInfor;
    public javax.swing.JButton btnRoomManage;
    public javax.swing.JButton btnRoomMap;
    public javax.swing.JButton btnStatistical;
    public javax.swing.JButton btnUserManagement;
    private javax.swing.ButtonGroup buttonGroupDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel panelBoderRoomManage;
    public javax.swing.JPanel panelBoderRoomMap;
    public javax.swing.JPanel panelBorderCusMgt;
    public javax.swing.JPanel panelBorderInforPerson;
    public javax.swing.JPanel panelBorderPayment;
    public javax.swing.JPanel panelBorderStatis;
    public javax.swing.JPanel panelBorderUserMgt;
    public javax.swing.JPanel panelCustomerManage;
    private javax.swing.JPanel panelLogo;
    public javax.swing.JPanel panelPayment;
    private javax.swing.JPanel panelRoomManage;
    public javax.swing.JPanel panelRoomMap;
    public javax.swing.JPanel panelScreen;
    public javax.swing.JPanel panelStatistical;
    public javax.swing.JPanel panelUserManage;
    public javax.swing.JPanel panelnforPerson;
    // End of variables declaration//GEN-END:variables
}
