/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.common.InfoRoom;
import java.awt.Color;

/**
 *
 * @author lminh
 */
public class FormRoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormRoomPanel
     */
    public FormRoomPanel() {
        initComponents();
    }
    
    
    public void setLabelRoomNumber(String roomNumber) {
        labelRoomNumber.setText("PHÒNG" + roomNumber);
    }
    
    public void setLabelRoomQuantity(String roomQuantity) {
        labelRoomQuantity.setText("Kiểu phòng: " + roomQuantity);
    }
    
    public void setLabelRoomType(String roomType) {
        labelRoomType.setText("Loại phòng: " + roomType);
    }
    
    public void setLabelRoomStatus(String roomStatus) {
        labelRoomStatus.setText(roomStatus);
    }
    
    public void setBgrPanelStatusRoom(Color color) {
        panelStatusRoom.setBackground(color);
//        labelRoomQuantity.setBackground(color);
//        labelRoomType.setBackground(color);
//        labelRoomStatus.setBackground(color);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuItemBookRoom = new javax.swing.JMenuItem();
        menuItemRoomDetails = new javax.swing.JMenuItem();
        labelRoomNumber = new javax.swing.JLabel();
        panelStatusRoom = new javax.swing.JPanel();
        labelRoomType = new javax.swing.JLabel();
        labelRoomStatus = new javax.swing.JLabel();
        labelRoomQuantity = new javax.swing.JLabel();

        menuItemBookRoom.setText("Đặt phòng");
        jPopupMenu1.add(menuItemBookRoom);

        menuItemRoomDetails.setText("Xóa phòng");
        jPopupMenu1.add(menuItemRoomDetails);

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(150, 150));
        setMinimumSize(new java.awt.Dimension(150, 150));
        setPreferredSize(new java.awt.Dimension(150, 150));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        labelRoomNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelRoomNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoomNumber.setText("Phòng 101 (Ví dụ)");
        add(labelRoomNumber, java.awt.BorderLayout.PAGE_START);

        panelStatusRoom.setBackground(new java.awt.Color(255, 255, 255));
        panelStatusRoom.setPreferredSize(new java.awt.Dimension(150, 251));
        panelStatusRoom.setLayout(new java.awt.BorderLayout());

        labelRoomType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoomType.setText("Loại phòng: VIP");
        panelStatusRoom.add(labelRoomType, java.awt.BorderLayout.PAGE_START);

        labelRoomStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoomStatus.setText("ĐANG TRỐNG");
        panelStatusRoom.add(labelRoomStatus, java.awt.BorderLayout.PAGE_END);

        labelRoomQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRoomQuantity.setText("Kiểu phòng: Đơn");
        panelStatusRoom.add(labelRoomQuantity, java.awt.BorderLayout.CENTER);

        add(panelStatusRoom, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jPopupMenu1.show(this, 20, 30);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel labelRoomNumber;
    private javax.swing.JLabel labelRoomQuantity;
    private javax.swing.JLabel labelRoomStatus;
    private javax.swing.JLabel labelRoomType;
    private javax.swing.JMenuItem menuItemBookRoom;
    private javax.swing.JMenuItem menuItemRoomDetails;
    public javax.swing.JPanel panelStatusRoom;
    // End of variables declaration//GEN-END:variables
}
