/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 *
 * @author lminh
 */
public class RoomMapPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomMapPanel
     */
    public RoomMapPanel() {
        initComponents();
//        jScrollPane1.add(new FormRoomPanel());
    }
    
    public void deleteFormRoomPanel() {
        panelSonListRoom.remove(formRoomPanelSample);
    }
    
    public void addFormRoomPanel(JPanel jPanel) {
        panelSonListRoom.add(jPanel);
    }
    
    public void setLabelRoomAvail(String text) {
        labelTotalRoomAvail.setText(text);
    }
    
    public void setLabelRoomNotAvail(String text) {
        labelTotalRoomNotAvail.setText(text);
    }
    
    public void setLabelRoomBusy(String text) {
        labelTotalRoomBusy.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelShowListRoom = new javax.swing.JPanel();
        panelSonListRoom = new javax.swing.JPanel();
        formRoomPanelSample = new com.mycompany.view.FormRoomPanel();
        panelTotlaRoom = new javax.swing.JPanel();
        panelTotalRoomAvail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelTotalRoomAvail = new javax.swing.JLabel();
        panelTotalRoomNotAvail = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelTotalRoomNotAvail = new javax.swing.JLabel();
        panelTotalRoomBusy = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelTotalRoomBusy = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelShowListRoom.setBackground(new java.awt.Color(204, 204, 204));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        panelShowListRoom.setLayout(flowLayout1);

        panelSonListRoom.setLayout(new java.awt.GridLayout(0, 5, 10, 10));
        panelSonListRoom.add(formRoomPanelSample);

        panelShowListRoom.add(panelSonListRoom);

        jScrollPane1.setViewportView(panelShowListRoom);

        panelTotlaRoom.setBackground(new java.awt.Color(255, 255, 255));
        panelTotlaRoom.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        panelTotalRoomAvail.setBackground(new java.awt.Color(153, 255, 153));
        panelTotalRoomAvail.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("PHÒNG TRỐNG");

        labelTotalRoomAvail.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTotalRoomAvail.setText("(20)");

        javax.swing.GroupLayout panelTotalRoomAvailLayout = new javax.swing.GroupLayout(panelTotalRoomAvail);
        panelTotalRoomAvail.setLayout(panelTotalRoomAvailLayout);
        panelTotalRoomAvailLayout.setHorizontalGroup(
            panelTotalRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalRoomAvailLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalRoomAvail)
                .addContainerGap())
        );
        panelTotalRoomAvailLayout.setVerticalGroup(
            panelTotalRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalRoomAvailLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTotalRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelTotalRoomAvail))
                .addGap(43, 43, 43))
        );

        panelTotlaRoom.add(panelTotalRoomAvail);

        panelTotalRoomNotAvail.setBackground(new java.awt.Color(255, 102, 102));
        panelTotalRoomNotAvail.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("PHÒNG ĐÃ ĐẶT");

        labelTotalRoomNotAvail.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTotalRoomNotAvail.setText("(15)");

        javax.swing.GroupLayout panelTotalRoomNotAvailLayout = new javax.swing.GroupLayout(panelTotalRoomNotAvail);
        panelTotalRoomNotAvail.setLayout(panelTotalRoomNotAvailLayout);
        panelTotalRoomNotAvailLayout.setHorizontalGroup(
            panelTotalRoomNotAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalRoomNotAvailLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalRoomNotAvail)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelTotalRoomNotAvailLayout.setVerticalGroup(
            panelTotalRoomNotAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalRoomNotAvailLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelTotalRoomNotAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalRoomNotAvail)
                    .addComponent(jLabel2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelTotlaRoom.add(panelTotalRoomNotAvail);

        panelTotalRoomBusy.setBackground(new java.awt.Color(0, 204, 204));
        panelTotalRoomBusy.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("PHÒNG BẬN");

        labelTotalRoomBusy.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTotalRoomBusy.setText("(15)");

        javax.swing.GroupLayout panelTotalRoomBusyLayout = new javax.swing.GroupLayout(panelTotalRoomBusy);
        panelTotalRoomBusy.setLayout(panelTotalRoomBusyLayout);
        panelTotalRoomBusyLayout.setHorizontalGroup(
            panelTotalRoomBusyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalRoomBusyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalRoomBusy)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelTotalRoomBusyLayout.setVerticalGroup(
            panelTotalRoomBusyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalRoomBusyLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTotalRoomBusyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelTotalRoomBusy))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelTotlaRoom.add(panelTotalRoomBusy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTotlaRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTotlaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.view.FormRoomPanel formRoomPanelSample;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalRoomAvail;
    private javax.swing.JLabel labelTotalRoomBusy;
    private javax.swing.JLabel labelTotalRoomNotAvail;
    private javax.swing.JPanel panelShowListRoom;
    private javax.swing.JPanel panelSonListRoom;
    private javax.swing.JPanel panelTotalRoomAvail;
    private javax.swing.JPanel panelTotalRoomBusy;
    private javax.swing.JPanel panelTotalRoomNotAvail;
    private javax.swing.JPanel panelTotlaRoom;
    // End of variables declaration//GEN-END:variables
}
