/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.panel;

import com.mycompany.model.Booking;

import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import com.mycompany.model.Customer;
import com.mycompany.service.Iplm.CustomerServiceIplm;
import java.awt.event.MouseAdapter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.mycompany.service.ICustomerService;
import java.awt.event.ActionListener;

/**
 *
 * @author lminh
 */
public class PaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     */
    private ICustomerService customer = new CustomerServiceIplm();
    private List<Customer> customers = customer.getAllCustomers();
    
    public PaymentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchCustomer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCustomer = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBooking = new javax.swing.JTable();
        btnPayment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(800, 600));

        txtSearchCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCustomerKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Số điện thoại");

        listCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listCustomer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCustomer.setVisibleRowCount(5);
        jScrollPane2.setViewportView(listCustomer);

        tableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Số phòng", "Đơn giá / h", "Thời gian đặt phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBooking);
        if (tableBooking.getColumnModel().getColumnCount() > 0) {
            tableBooking.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableBooking.getColumnModel().getColumn(1).setPreferredWidth(20);
            tableBooking.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        btnPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPayment.setText("Thanh toán");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên khách hàng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email");

        txtCustomerName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustomerName.setEnabled(false);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày sinh");

        txtBirthday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBirthday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBirthday.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Giới tính");

        txtSex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSex.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBirthday)
                                    .addComponent(txtEmail)
                                    .addComponent(txtCustomerName)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtSearchCustomer)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52)
                                .addComponent(txtSex, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnPayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCustomerKeyReleased
        // TODO add your handling code here:
        searchListCustomer(this.customers,getSearchCustomerPhoneNumber());
    }//GEN-LAST:event_txtSearchCustomerKeyReleased
    
    public String getSearchCustomerPhoneNumber() {
        return txtSearchCustomer.getText();
    }

    
    public void setListCustomer(List<Customer> customers) {
        
        DefaultListModel defaultListModel = new DefaultListModel();
        customers.stream().forEach((t) -> {
            String customerPhoneNumber = t.getPhoneNumber();
            defaultListModel.addElement(customerPhoneNumber);
        });
        this.listCustomer.setModel(defaultListModel);
    }
    
    public void searchListCustomer(List<Customer> customers, String searchCustomer) {
        DefaultListModel defaultListModel = new DefaultListModel();
        
        customers.stream().forEach((t) -> {
           if (t.getPhoneNumber().contains(searchCustomer)) {
               defaultListModel.addElement(t.getPhoneNumber());
           } 
        });
        this.listCustomer.setModel(defaultListModel);
    }
    
    public void setTableBooking(List<Booking> bookings) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableBooking.getModel();
        defaultTableModel.setRowCount(0);
        for(Booking booking : bookings) {
            defaultTableModel.addRow(new Object[] {
                    booking.getCustomer().getName(),
                    booking.getRoom().getRoomNumber(),
                    booking.getRoom().getPrice(),
                    booking.getTimeBooking()
            });
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        
        for (int i = 0; i < tableBooking.getColumnCount(); i++) {
            tableBooking.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    
    public void setName(String name) {
        txtCustomerName.setText(name);
    } 
    
    public void setBirthday(LocalDate birthday) {
        String birthdayString = birthday.toString();
        txtBirthday.setText(birthdayString);
    }
     
    public void setEmail(String email) {
        txtEmail.setText(email);
    }
    
    public void setSex (String sex) {
        txtSex.setText(sex);
    }
    
    public void setPhoneNumbe(String phoneNumber) {
        txtSearchCustomer.setText(phoneNumber);
    }
    
    public void setSelectionListCustomer(MouseAdapter mouseAdapter) {
        listCustomer.addMouseListener(mouseAdapter);
    }

    public String getCustomerPhoneNumber() {
        return listCustomer.getSelectedValue();
    }
    
    public void setBtnPayment(ActionListener listener) {
        btnPayment.addActionListener(listener);
    } 
    
    public String getSelectionValueBooking() {
        return (String) tableBooking.getValueAt(tableBooking.getSelectedRow(), 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listCustomer;
    private javax.swing.JTable tableBooking;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSearchCustomer;
    private javax.swing.JTextField txtSex;
    // End of variables declaration//GEN-END:variables
}
