/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.panel;

import com.mycompany.model.Booking;
import java.util.List;
import javax.swing.DefaultListModel;
import com.mycompany.model.Customer;
import com.mycompany.service.ICustomer;
import com.mycompany.service.Iplm.CustomerServiceIplm;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lminh
 */
public class PaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     */
    private ICustomer customer = new CustomerServiceIplm();
    private List<Customer> customers = customer.getAllCustomers();
    
    public PaymentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchCustomer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCustomer = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBooking = new javax.swing.JTable();
        btnPayment = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(800, 600));

        txtSearchCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCustomerKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên khách hàng");

        listCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(listCustomer);

        tableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Số phòng", "Đơn giá / h", "Thời gian đặt phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBooking);
        if (tableBooking.getColumnModel().getColumnCount() > 0) {
            tableBooking.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableBooking.getColumnModel().getColumn(1).setPreferredWidth(20);
            tableBooking.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        btnPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPayment.setText("Thanh toán");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPayment)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCustomerKeyReleased
        // TODO add your handling code here:
        searchListCustomer(this.customers,getSearchCustomerName());
    }//GEN-LAST:event_txtSearchCustomerKeyReleased
    
    public String getSearchCustomerName() {
        return txtSearchCustomer.getText();
    }
    
    public String getCustomerName() {
        return listCustomer.getSelectedValue();
    }
    
    public void setListCustomer(List<Customer> customers) {
        
        DefaultListModel defaultListModel = new DefaultListModel();
        customers.stream().forEach((t) -> {
            String customerName = t.getName();
            defaultListModel.addElement(customerName);
        });
        
        this.listCustomer.setModel(defaultListModel);
    }
    
    public void searchListCustomer(List<Customer> customers, String searchCustomer) {
        DefaultListModel defaultListModel = new DefaultListModel();
        
        customers.stream().forEach((t) -> {
           if (t.getName().toLowerCase().contains(searchCustomer.toLowerCase())) {
               defaultListModel.addElement(t.getName());
           } 
        });
        this.listCustomer.setModel(defaultListModel);
    }
    
    public void setTableBooking(List<Booking> bookings) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableBooking.getModel();
        
        for (int i = 0; i < bookings.size(); i++) {
            Booking booking = bookings.get(i);
            defaultTableModel.setValueAt(booking.getCustomer().getName(), i, 0);
            defaultTableModel.setValueAt(booking.getRoom().getRoomNumber(), i, 1);
            defaultTableModel.setValueAt(booking.getRoom().getPrice(), i, 2);
            defaultTableModel.setValueAt(booking.getTimeBooking(), i, 3);
        }
        
        tableBooking.setModel(defaultTableModel);
        
    }
    
    public void getSelectionListCustomer(MouseAdapter mouseAdapter) {
        listCustomer.addMouseListener(mouseAdapter);
    }
    
//    public void set

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listCustomer;
    private javax.swing.JTable tableBooking;
    private javax.swing.JTextField txtSearchCustomer;
    // End of variables declaration//GEN-END:variables
}
